# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morbilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nom_departamento', models.CharField(choices=[('Ahuachapan', 'Ahuachapan'), ('Sonsonate', 'Sonsonate'), ('Santa ana', 'Santa ana'), ('Cabanas', 'Cabanas'), ('Chalatenango', 'Chalatenango'), ('Cuscatlan', 'Cuscatlan'), ('La Libertad', 'La Libertad'), ('La Paz', 'La Paz'), ('San Salvador', 'San Salvador'), ('San Vicente', 'San Vicente'), ('Morazan', 'Morazan'), ('San Miguel', 'San Miguel'), ('Usulutan', 'Usulutan'), ('La Union', 'La Union')], default='San Salvador', max_length=50)),
                ('anio', models.IntegerField(choices=[(2014, '2014'), (2015, '2015')], default=2014)),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=15)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
